### ISSUE TITLE
mkSnapshotMatrix not sorted alphanumerically

### ISSUE THREAD

**Issue by Tony607** [UCF-ERAU-OH-Research-Group/POD-RBF#1]
Hi,
The output of `os.listdir` might not be sorted alphanumerically.
https://github.com/UCF-ERAU-OH-Research-Group/POD-RBF/blob/master/pod_rbf/pod_rbf.py#L256

Might need to add `sorted()`.
```python
files = [f for f in sorted(os.listdir(dirpath)) if os.path.isfile(os.path.join(dirpath, f))]
```

**Comment by kylebeggs** [comment]
Thank you very much, this is fixed in v1.1.1! Sorry for the delay, I wish I could auto-assign issues to me so I receive notifications.
